# Generated by Django 6.0.5 on 2026-05-28 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('algorithm', models.CharField(choices=[('nn', 'Nearest Neighbor'), ('2opt', '2-Opt'), ('aco', 'Ant Colony Optimization'), ('all', 'All Algorithms')], max_length=10)),
                ('result_path', models.JSONField(default=list)),
                ('total_distance', models.FloatField(default=0.0)),
                ('execution_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points', models.ManyToManyField(related_name='tasks', to='routes.deliverypoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlgorithmBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(max_length=50)),
                ('execution_time', models.FloatField()),
                ('total_distance', models.FloatField()),
                ('path', models.JSONField(default=list)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='routes.routetask')),
            ],
        ),
    ]
